CREATE TABLE IF NOT EXISTS proceso_busquedas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    etapa VARCHAR(100) NOT NULL,
    descripcion VARCHAR(200) NOT NULL,
    creditos INT NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    fecha_alta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ultima_mod TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;