CREATE TABLE IF NOT EXISTS reinicio_contrasenia (
    id INT AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(200) NOT NULL,
    email VARCHAR(100) NOT NULL,
    used BOOLEAN DEFAULT FALSE,
    fecha_alta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_exp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_usuario INT NULL,
    FOREIGN KEY (id_usuario) 
        REFERENCES usuarios(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB;